#!/bin/sh

# ubuntu image with node, npm and tools
docker buildx build -t pi:latest .

# pi itself
./bash -c "npm install -g @mariozechner/pi-coding-agent"

# pi packages
./bash -c "pi install npm:pi-subagents"
./bash -c "npx pi-subagents"
